# Generated by Django 4.2.9 on 2024-01-14 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(default='Модель №1', max_length=255, verbose_name='Модель автомобиля')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('price', models.IntegerField(default=99999, verbose_name='Стоимость (руб./час)')),
                ('description', models.TextField(blank=True, default='', max_length=1000, verbose_name='Сведения')),
                ('photo', models.FileField(blank=True, default='', upload_to='cars/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('rent_time', models.IntegerField(default=600, verbose_name='Время аренды (в минутах)')),
                ('total_price', models.IntegerField(default=-1, editable=False, verbose_name='Общая сумма')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.cars', verbose_name='Автомобиль')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
